### ISSUE TITLE
Error: Input does not match schema

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Barcodes#21]
This is probably related to `Simplified`, but it was observed here.
It was noticed by @PatrykSzwer .

### Steps to reproduce
1. Go to http://localhost:8080/barcodes/barcodes/
2. Write something for "Identifies".

You will see an error:
![image](https://user-images.githubusercontent.com/25042256/28517522-ee9c4cec-7064-11e7-96b9-f2e1406a47d1.png)

```
Starcounter.DbException occurred
  HResult=0x80131500
  Message=ScErrSchemaCodeMismatch (SCERR4177): Operation failed because input does not match schema. CLR Class is not loaded for table CssVariablesManager.CssCollection
Version: 2.3.1.6852.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4177.
  Source=Starcounter(2.3.1.6852)
  StackTrace:
   at Starcounter.Binding.Bindings.CreateExceptionOnTypeDefNotFound(Int32 tableId)
   at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(Int32 tableId)
   at Starcounter.Enumerator.MoveNext()
   at Starcounter.Query.Execution.FullTableScan.MoveNext()
   at Starcounter.Json.Array_InitializeAfterImplicitConversion(Json parent, TObjArr template)
   at Starcounter.Templates.TArray`1.BoundOrUnboundSet(Json parent, Arr`1 value)
   at Barcodes.BarcodePage.set_FoundIdentifiers(Arr`1 value) in C:\Users\Mihai\Desktop\New folder (5)\Barcodes\src\Barcodes\obj\x64\Debug\ViewModels\ViewModels\BarcodePage.json:line 10
   at Barcodes.BarcodePage.Handle(IdentifiesName Action) in C:\Users\Mihai\Desktop\New folder (5)\Barcodes\src\Barcodes\ViewModels\BarcodePage.json.cs:line 37
   at Barcodes.BarcodePage.JsonByExample.Schema.<>c.<.ctor>b__0_5(Json pup, Input`1 input)
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input)
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value)
   at Starcounter.XSON.DefaultPatchHandler.<>c__DisplayClass0_0.<Handle>b__0()
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action)
   at Starcounter.Transaction.Scope(Action action)
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action)
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value)
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection)
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount)
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount)
   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__8_0(Session session, Request request)
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack)
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req)
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req)
```

**Comment by warpech** [comment]
I cannot reproduce this problem. Is the Barcodes app the only app running?

Can you try on an empty database and see if that helps?

**Comment by Mihaiii** [comment]
Yes, Barcodes was the only app running.
I deleted the database and after that it worked as expected, without this error.

**Comment by warpech** [comment]
Typically, this is a situation when this happens: https://github.com/StarcounterApps/HelloWorld/issues/50

You have an app that has a definition of some class (not in Simplified), you store an instance of that class in the database and then you stop the app that has the definition. 

Was this the case maybe?

**Comment by Mihaiii** [comment]
Might be, makes sense.
I'll leave this open in case @PatrykSzwer could provide more details (feel free to close it, if you consider it's the case).

**Comment by PatrykSzwer** [comment]
I investigated this a little more. Problem is occurring here:
```cs
void Handle(Input.IdentifiesName Action) {
            this.Data.Identifies = null;
            this.FoundIdentifiers = Db.SQL("SELECT s FROM Simplified.Ring1.Something s WHERE Name LIKE ? Fetch ?", Action.Value + "%", 10);
        }
```

With my current db version, when trying to call db (in Administrator tool) with query: `SELECT * FROM Simplified.Ring1.Something`   I'm getting error like this: 
![image](https://user-images.githubusercontent.com/25042256/28756623-7af101c6-7572-11e7-8a0a-0aef68209601.png)

Seems like some collision with old CssThemer.

**Comment by warpech** [comment]
This make is quite obvious, thanks!

There was an instance of `CssThemer.CssTheme` in your database. But in the app, that class was replaced by another class: https://github.com/StarcounterApps/Simplified/blob/master/Ring6/CssVariablesManager/CssCollection.cs

Starcounter **does not** do any automatic schema refactoring. If a class is renamed, you cannot access the data that was created usign the old name. You have to write a script that copies the data to the new name.

I think it can be closed.
